# Generated by Django 3.0.7 on 2020-06-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootWear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufac_name', models.CharField(max_length=30)),
                ('shoe_style', models.CharField(choices=[('SN', 'Sneaker'), ('BT', 'Boot'), ('SL', 'Sandal'), ('DR', 'Dress'), ('OT', 'Other')], default='SN', max_length=10)),
                ('Shoe_Color', models.CharField(choices=[('RD', 'Red'), ('OR', 'Orange'), ('YE', 'Yellow'), ('GR', 'Green'), ('BL', 'Blue'), ('IN', 'Indigo'), ('VT', 'Violet'), ('WH', 'White'), ('BL', 'Black')], default='RD', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_size', models.IntegerField()),
                ('brand_name', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=100)),
                ('fasten_type', models.CharField(max_length=30)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shoestore_app.FootWear')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shoestore_app.FootWear')),
                ('shoe_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shoestore_app.FootWear')),
            ],
        ),
    ]
